schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "rotoforge_ai"
version = "1.1.1"
name = "RotoForge AI"
tagline = "Uses metas segment-anything model (SAM) + some other stuff to make rotoscoping fast af"
maintainer = "MagnumVD <magnumvd@gmx.net>"
# Supported types: "add-on", "theme"
type = "add-on"

# # Optional: link to documentation, support, source files, etc
website = "https://github.com/MagnumVD/RotoForge-AI"

# # Optional: tag list defined by Blender and server, see:
# # https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Compositing"]

blender_version_min = "4.2.0"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]
# # Optional: required by some licenses.
copyright = [
  "2024 Vincent Dorenkamp",
]

# # Optional: list of supported platforms. If omitted, the extension will be available in all operating systems.
platforms = ["windows-x64", "linux-x64"]
# # List of possible platforms: "windows-x64", "macos-arm64", "linux-x64", "windows-arm64", "macos-x64"

# # Optional: bundle 3rd party Python modules.
# # https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
wheels = [
  "./wheels/colorama-0.4.6-py2.py3-none-any.whl",
  "./wheels/filelock-3.20.0-py3-none-any.whl",
  "./wheels/fsspec-2025.9.0-py3-none-any.whl",
  "./wheels/markupsafe-3.0.3-cp311-cp311-win_amd64.whl",
  "./wheels/mpmath-1.3.0-py3-none-any.whl",
  "./wheels/networkx-3.5-py3-none-any.whl",
  "./wheels/packaging-25.0-py3-none-any.whl",
  "./wheels/pillow-12.0.0-cp311-cp311-win_amd64.whl",
  "./wheels/pyyaml-6.0.3-cp311-cp311-win_amd64.whl",
  "./wheels/safetensors-0.6.2-cp38-abi3-win_amd64.whl",
  "./wheels/segment_anything_hq-1.0-py3-none-any.whl",
  "./wheels/sympy-1.14.0-py3-none-any.whl",
  "./wheels/timm-1.0.21-py3-none-any.whl",
  "./wheels/torch-2.8.0-cp311-cp311-win_amd64.whl",
  "./wheels/torchvision-0.23.0-cp311-cp311-win_amd64.whl",
  "./wheels/tqdm-4.67.1-py3-none-any.whl",
  "./wheels/typing_extensions-4.15.0-py3-none-any.whl",
]

# # Optional: add-ons can list which resources they will require:
# # * files (for access of any filesystem operations)
# # * network (for internet access)
# # * clipboard (to read and/or write the system clipboard)
# # * camera (to capture photos and videos)
# # * microphone (to capture audio)
# #
# # If using network, remember to also check `bpy.app.online_access`
# # https://docs.blender.org/manual/en/dev/advanced/extensions/addons.html#internet-access
# #
# # For each permission it is important to also specify the reason why it is required.
# # Keep this a single short sentence without a period (.) at the end.
# # For longer explanations use the documentation or detail page.
#
# [permissions]
network = "Need to download python packages and models"
files = "Load/Save python libs, models, masks"

# # Optional: advanced build settings.
# # https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
# [build]
# # These are the default build excluded patterns.
# # You only need to edit them if you want different options.
# paths_exclude_pattern = [
#   "__pycache__/",
#   "/.git/",
#   "/*.zip",
# ]
